 const workersData = {
      Cleaning: [
    { 
      id: "cleaner1",
      name: "Sita Devi", 
      skill: "Deep Home Cleaner", 
      exp: "6 years of professional cleaning", 
      charges: "₹249/hr", 
      img: "/images/cleaner1.png",
      rating: 4.8,
      reviews: ["Excellent service", "House was spotless", "Very polite"],
      beforeAfter: { before: "/images/cleaning_before1.jpg", after: "/images/cleaning_after1.jpg" }
    },
    { 
      id: "cleaner2",
      name: "Ramesh Kumar", 
      skill: "Office Cleaning Expert", 
      exp: "3 years in corporate sanitization", 
      charges: "₹299/hr", 
      img: "/images/cleaner2.png",
      rating: 4.6,
      reviews: ["Very punctual", "Great for office spaces", "Quick service"],
      beforeAfter: { before: "/images/cleaning_before2.jpg", after: "/images/cleaning_after2.jpg" }
    },
    { 
      id: "cleaner3",  
      name: "Meena Sharma",
      skill: "Kitchen & Bathroom Specialist",
      exp: "5 years in hygiene services",
      charges: "₹349/hr",
      img: "/images/cleaner3.png",
      rating: 4.6,
      reviews: ["Very punctual", "Great for office spaces", "Quick service"],
      beforeAfter: { before: "/images/cleaning_before2.jpg", after: "/images/cleaning_after2.jpg" }  
     },
    { 
      id: "cleaner4",  
      name: "Asha Patel",
      skill: "Move-In/Move-Out Cleaning",
      exp: "7 years of service",
      charges: "₹399/hr",
      img: "/images/cleaner4.png",
      rating: 4.6,
      reviews: ["Very punctual", "Great for office spaces", "Quick service"],
      beforeAfter: { before: "/images/cleaning_before2.jpg", after: "/images/cleaning_after2.jpg" }    
    },
    { 
      id: "cleaner5", 
      name: "Lakshmi Rao",
      skill: "Window & Glass Cleaning",
      exp: "4 years in residential services", 
      charges: "₹279/hr", 
      img: "/images/cleaner5.png",
      rating: 4.6,
      reviews: ["Very punctual", "Great for office spaces", "Quick service"],
      beforeAfter: { before: "/images/cleaning_before2.jpg", after: "/images/cleaning_after2.jpg" }     
      },
    { 
      id: "cleaner6",  
      name: "Nandini Singh",
      skill: "Carpet & Upholstery Cleaner",
      exp: "6 years in deep cleaning",
      charges: "₹329/hr",
      img: "/images/cleaner6.png" ,
      rating: 4.6,
      reviews: ["Very punctual", "Great for office spaces", "Quick service"],
      beforeAfter: { before: "/images/cleaning_before2.jpg", after: "/images/cleaning_after2.jpg" }    
    },
    { 
      id: "cleaner7",  
      name: "Priya Iyer", 
      skill: "Eco-Friendly Cleaning Specialist",
      exp: "3 years in organic cleaning", 
      charges: "₹299/hr",
      img: "/images/cleaner7.png",
      rating: 4.6,
      reviews: ["Very punctual", "Great for office spaces", "Quick service"],
      beforeAfter: { before: "/images/cleaning_before2.jpg", after: "/images/cleaning_after2.jpg" }    
    },
    { 
        id: "cleaner8",      
      name: "Geeta Verma",
      skill: "Floor & Tile Cleaning Expert",
      exp: "5 years of experience",
      charges: "₹349/hr",
      img: "/images/cleaner8.png",
      rating: 4.6,
      reviews: ["Very punctual", "Great for office spaces", "Quick service"],
      beforeAfter: { before: "/images/cleaning_before2.jpg", after: "/images/cleaning_after2.jpg" }    
     },
  ],
  Repairs: [
    {   
      id: "repair1",
      name: "Ravi Kumar", 
      skill: "Electrician", 
      exp: "5 years in wiring & appliance repair", 
      charges: "₹299/hr", 
      img: "/images/electrician1.png",
      rating: 4.7,
      reviews: ["Fixed wiring issues quickly", "Very knowledgeable", "Affordable"],
      beforeAfter: { before: "/images/repair_before1.jpg", after: "/images/repair_after1.jpg" }
    },
    {   
      id: "repair2",
      name: "vikram Singh", 
      skill: "Plumber", 
      exp: "4 years in pipe fitting & leak repair", 
      charges: "₹249/hr", 
      img: "/images/plumber1.png",
      rating: 4.5,
      reviews: ["Stopped leakage perfectly", "Clean work", "Quick response"],
      beforeAfter: { before: "/images/repair_before2.jpg", after: "/images/repair_after2.jpg" }
    },
    { 
      id: "repair3",  
      name: "Anil Mehta",
      skill: "AC & Fridge Repair",
      exp: "6 years in appliance repair",
      charges: "₹449/hr", 
      img: "/images/repair1.png",
      rating: 4.5,
      reviews: ["Stopped leakage perfectly", "Clean work", "Quick response"],
      beforeAfter: { before: "/images/repair_before2.jpg", after: "/images/repair_after2.jpg" }
     },
    { 
        id: "repair4",  
      name: "Sunil Reddy", 
      skill: "General Handyman",
      exp: "8 years in home repairs", 
      charges: "₹299/hr",
       img: "/images/handyman.png",
      rating: 4.5,
      reviews: ["Stopped leakage perfectly", "Clean work", "Quick response"],
      beforeAfter: { before: "/images/repair_before2.jpg", after: "/images/repair_after2.jpg" }
    },
    { 
      id: "repair5", 
      name: "Kiran Das",
      skill: "Carpenter", 
      exp: "7 years of woodwork & furniture fixes",
      charges: "₹399/hr", 
      img: "/images/carpenter1.png",
      rating: 4.5,
      reviews: ["Stopped leakage perfectly", "Clean work", "Quick response"],
      beforeAfter: { before: "/images/repair_before2.jpg", after: "/images/repair_after2.jpg" }
    },
    { 
      id: "repair6", 
      name: "Ajay Nair",
      skill: "Computer & Laptop Repair",
      exp: "5 years in IT hardware support",
      charges: "₹349/hr",
      img: "/images/repair2.png" ,
      rating: 4.5,
      reviews: ["Stopped leakage perfectly", "Clean work", "Quick response"],
      beforeAfter: { before: "/images/repair_before2.jpg", after: "/images/repair_after2.jpg" }
    },
    { 
      id: "repair7", 
      name: "Mohit Chauhan",
      skill: "Water Purifier Technician",
      exp: "4 years in RO system servicing",
      charges: "₹329/hr", 
      img: "/images/repair3.png",
      rating: 4.5,
      reviews: ["Stopped leakage perfectly", "Clean work", "Quick response"],
      beforeAfter: { before: "/images/repair_before2.jpg", after: "/images/repair_after2.jpg" }  
    },
    { 
      id: "repair8",  
      name: "Farhan Ali",
      skill: "Refrigerator & Washing Machine Expert",
      exp: "6 years in appliance services", 
      charges: "₹449/hr",
      img: "/images/repair4.png",
      rating: 4.5,
      reviews: ["Stopped leakage perfectly", "Clean work", "Quick response"],
      beforeAfter: { before: "/images/repair_before2.jpg", after: "/images/repair_after2.jpg" }
     },
  ],
    Installations: [
    { 
      id: "install1",
      name: "Amit Sharma", 
      skill: "TV & Entertainment Setup", 
      exp: "5 years experience", 
      charges: "₹349/hr", 
      img: "/images/install1.png",
      rating: 4.4,
      reviews: ["Set up my TV perfectly", "Clean wiring", "Explained controls well"],
      beforeAfter: { before: "/images/install_before1.jpg", after: "/images/install_after1.jpg" }
    },
    { 
      id: "install2",
      name: "Deepak Joshi",
      skill: "Furniture Assembly Expert",
      exp: "3 years in modular furniture installation",
      charges: "₹299/hr",
      img: "/images/install2.png",
      rating: 4.5,
      reviews: ["Very professional", "Work finished on time", "Neat job"],
      beforeAfter: { before: "/images/install_before2.jpg", after: "/images/install_after2.jpg" }
    },
    { 
      id: "install3",
      name: "Harish Naidu", 
      skill: "New Appliance Installer", 
      exp: "6 years in home appliance setup", 
      charges: "₹399/hr", 
      img: "/images/install4.png",
      rating: 4.6,
      reviews: ["Quick installation", "Explained usage well", "Friendly worker"],
      beforeAfter: { before: "/images/install_before3.jpg", after: "/images/install_after3.jpg" }
    },
    { 
      id: "install4",  
      name: "Pooja Verma",
      skill: "Light & Fan Installation",
      exp: "4 years in electrical fitting", 
      charges: "₹249/hr",
      img: "/images/install3.png",
      rating: 4.6,
      reviews: ["Quick installation", "Explained usage well", "Friendly worker"],
      beforeAfter: { before: "/images/install_before3.jpg", after: "/images/install_after3.jpg" }
    },
    { 
      id: "install5",  
      name: "Rajeev Menon", 
      skill: "Smart Home Setup",
      exp: "4 years in IoT device installations",
      charges: "₹449/hr",
      img: "/images/install5.png",
      rating: 4.6,
      reviews: ["Quick installation", "Explained usage well", "Friendly worker"],
      beforeAfter: { before: "/images/install_before3.jpg", after: "/images/install_after3.jpg" } 
    },
    { 
      id: "install6",  
      name: "Shalini Gupta",
      skill: "CCTV & Security Systems",
      exp: "5 years in surveillance setup",
      charges: "₹499/hr",
      img: "/images/install6.png",
      rating: 4.6,
      reviews: ["Quick installation", "Explained usage well", "Friendly worker"],
      beforeAfter: { before: "/images/install_before3.jpg", after: "/images/install_after3.jpg" } 
    },
    { 
      id: "install7",  
      name: "Ankush Batra",
      skill: "Kitchen Appliance Installer",
      exp: "6 years in modular kitchens", 
      charges: "₹399/hr",
      img: "/images/install7.png",
      rating: 4.6,
      reviews: ["Quick installation", "Explained usage well", "Friendly worker"],
      beforeAfter: { before: "/images/install_before3.jpg", after: "/images/install_after3.jpg" } 
    },
    { 
      id: "install8",  
      name: "Rohit Malhotra", 
      skill: "Water Heater & Geyser Setup",
      exp: "4 years of service",
      charges: "₹349/hr",
      img: "/images/install8.png",
      rating: 4.6,
      reviews: ["Quick installation", "Explained usage well", "Friendly worker"],
      beforeAfter: { before: "/images/install_before3.jpg", after: "/images/install_after3.jpg" }
    },
  ],
    Painting: [
    { 
      id: "paint1",
      name: "Sanjay Kumar", 
      skill: "Interior Wall Painter", 
      exp: "7 years in residential painting", 
      charges: "₹399/hr", 
      img: "/images/painter1.png",
      rating: 4.9,
      reviews: ["Beautiful finish", "Walls look new again", "Great detailing"],
      beforeAfter: { before: "/images/paint_before1.jpg", after: "/images/paint_after1.jpg" }
    },
    { 
      id: "paint2",  
      name: "Anita Joshi", 
      skill: "Exterior Painting Specialist",
      exp: "6 years in outdoor paint work",
      charges: "₹449/hr",
      img: "/images/painter2.png",
      rating: 4.7,
      reviews: ["Smooth finish", "Durable paint", "Good color suggestions"],
      beforeAfter: { before: "/images/paint_before2.jpg", after: "/images/paint_after2.jpg" } 
    },
    { 
      id: "paint3",  
      name: "Rohit Singh",
      skill: "Decorative & Mural Painter", 
      exp: "5 years of creative painting",
      charges: "₹499/hr",
      img: "/images/painter3.png",
      rating: 4.7,
      reviews: ["Smooth finish", "Durable paint", "Good color suggestions"],
      beforeAfter: { before: "/images/paint_before2.jpg", after: "/images/paint_after2.jpg" }
        
    },
    { 
      id: "paint4",  
      name: "Meera Iyer",
      skill: "Wood & Furniture Painter",
      exp: "4 years in furniture finishing",
      charges: "₹399/hr",
      img: "/images/painter4.png", 
      rating: 4.7,
      reviews: ["Smooth finish", "Durable paint", "Good color suggestions"],
      beforeAfter: { before: "/images/paint_before2.jpg", after: "/images/paint_after2.jpg" }    
    },
    { 
      id: "paint5",  
      name: "Ajay Patel",
      skill: "Wallpaper & Textured Paint",
      exp: "3 years in specialty painting",
      charges: "₹349/hr",
      img: "/images/painter5.png",
      rating: 4.7,
      reviews: ["Smooth finish", "Durable paint", "Good color suggestions"],
      beforeAfter: { before: "/images/paint_before2.jpg", after: "/images/paint_after2.jpg" }     
    },
    { 
      id: "paint6",  
      name: "Sunita Reddy",
      skill: "Eco-Friendly Paint Specialist",
      exp: "4 years in green painting solutions", 
      charges: "₹429/hr",
      img: "/images/painter6.png",
      rating: 4.7,
      reviews: ["Smooth finish", "Durable paint", "Good color suggestions"],
      beforeAfter: { before: "/images/paint_before2.jpg", after: "/images/paint_after2.jpg" }
     },
    { 
      id: "paint7",  
      name: "Karan Mehta",
      skill: "Commercial Painter",
      exp: "6 years in office and retail painting",
      charges: "₹479/hr",
      img: "/images/painter7.png",
      rating: 4.7,
      reviews: ["Smooth finish", "Durable paint", "Good color suggestions"],
      beforeAfter: { before: "/images/paint_before2.jpg", after: "/images/paint_after2.jpg" }
   },
    { 
      id: "paint8",  
      name: "Pooja Sharma",
      skill: "Ceiling & Drywall Painter", 
      exp: "5 years experience",
      charges: "₹399/hr",
      img: "/images/painter8.png", 
      rating: 4.7,
      reviews: ["Smooth finish", "Durable paint", "Good color suggestions"],
      beforeAfter: { before: "/images/paint_before2.jpg", after: "/images/paint_after2.jpg" }
    },
  ],
    PackersandMovers: [
    { 
      id: "pack1",
      name: "Ravi Sharma", 
      skill: "Home Relocation Specialist", 
      exp: "8 years in domestic shifting", 
      charges: "₹599/hr", 
      img: "/images/packers1.png",
      rating: 4.7,
      reviews: ["Handled furniture with care", "Smooth move", "No damage"],
      beforeAfter: { before: "/images/move_before1.jpg", after: "/images/move_after1.jpg" }
    },
    { 
      id: "pack2",
      name: "Anil Verma", 
      skill: "Office Shifting Expert", 
      exp: "6 years experience", 
      charges: "₹649/hr", 
      img: "/images/packers2.png",
      rating: 4.6,
      reviews: ["Organized shifting", "Good packaging", "On-time delivery"],
      beforeAfter: { before: "/images/move_before2.jpg", after: "/images/move_after2.jpg" }
    },
    { 
      id: "pack3",  
      name: "Manoj Kumar",
      skill: "Furniture Dismantling & Assembly",
      exp: "5 years experience", 
      charges: "₹549/hr",
      img: "/images/packers3.png", 
      rating: 4.6,
      reviews: ["Organized shifting", "Good packaging", "On-time delivery"],
      beforeAfter: { before: "/images/move_before2.jpg", after: "/images/move_after2.jpg" }
    },
    { 
      id: "pack4",  
      name: "Sneha Gupta",
      skill: "Fragile Item Handling",
      exp: "4 years in delicate packing",
      charges: "₹599/hr",
      img: "/images/packers4.png", 
      rating: 4.6,
      reviews: ["Organized shifting", "Good packaging", "On-time delivery"],
      beforeAfter: { before: "/images/move_before2.jpg", after: "/images/move_after2.jpg" }  
    },
    { 
      id: "pack5",  
      name: "Amit Patel",
      skill: "Long-Distance Moving Specialist",
      exp: "7 years in interstate relocation",
      charges: "₹699/hr", 
      img: "/images/packers5.png",
      rating: 4.6,
      reviews: ["Organized shifting", "Good packaging", "On-time delivery"],
      beforeAfter: { before: "/images/move_before2.jpg", after: "/images/move_after2.jpg" }
     },
    { 
      id: "pack6",  
      name: "Rohit Yadav",
      skill: "Vehicle Transportation Expert",
      exp: "5 years in car/bike transport", 
      charges: "₹649/hr",
      img: "/images/packers6.png",
      rating: 4.6,
      reviews: ["Organized shifting", "Good packaging", "On-time delivery"],
      beforeAfter: { before: "/images/move_before2.jpg", after: "/images/move_after2.jpg" }  
    },
    { 
      id: "pack7",  
      name: "Kavita Nair",
      skill: "Packing Material Specialist",
      exp: "3 years in eco-friendly packing", 
      charges: "₹529/hr", 
      img: "/images/packers7.png",
      rating: 4.6,
      reviews: ["Organized shifting", "Good packaging", "On-time delivery"],
      beforeAfter: { before: "/images/move_before2.jpg", after: "/images/move_after2.jpg" }
     },
    { 
      id: "pack8",  
      name: "Deepak Singh",
      skill: "Storage & Warehouse Management", 
      exp: "6 years in goods storage", 
      charges: "₹579/hr", 
      img: "/images/packers8.png",
      rating: 4.6,
      reviews: ["Organized shifting", "Good packaging", "On-time delivery"],
      beforeAfter: { before: "/images/move_before2.jpg", after: "/images/move_after2.jpg" }  
    },
  ],
};
export default workersData;